export const domeImages = [
  // Numbered webp images (1-15)
  { id: '1', src: '/memories/1.webp', caption: 'Memory #1' },
  { id: '2', src: '/memories/2.webp', caption: 'Memory #2' },
  { id: '3', src: '/memories/3.webp', caption: 'Memory #3' },
  { id: '4', src: '/memories/4.webp', caption: 'Memory #4' },
  { id: '5', src: '/memories/5.webp', caption: 'Memory #5' },
  { id: '6', src: '/memories/6.webp', caption: 'Memory #6' },
  { id: '7', src: '/memories/7.webp', caption: 'Memory #7' },
  { id: '8', src: '/memories/8.webp', caption: 'Memory #8' },
  { id: '9', src: '/memories/9.webp', caption: 'Memory #9' },
  { id: '10', src: '/memories/10.webp', caption: 'Memory #10' },
  { id: '11', src: '/memories/11.webp', caption: 'Memory #11' },
  { id: '12', src: '/memories/12.webp', caption: 'Memory #12' },
  { id: '13', src: '/memories/13.webp', caption: 'Memory #13' },
  { id: '14', src: '/memories/14.webp', caption: 'Memory #14' },
  { id: '15', src: '/memories/15.webp', caption: 'Memory #15' },
  // Named jpeg images
  { id: 'barfi', src: '/memories/barfi.jpg', caption: 'Barfi' },
  { id: 'sem1', src: '/memories/sem1_lastday.jpg', caption: 'Semester 1 Last Day' },
  { id: 'sem2', src: '/memories/sem2_lastday.jpg', caption: 'Semester 2 Last Day' },
  { id: 'sem3', src: '/memories/sem3_lastday.jpg', caption: 'Semester 3 Last Day' },
  { id: 'sem4', src: '/memories/sem4_lastday.jpg', caption: 'Semester 4 Last Day' },
  { id: 'sem5', src: '/memories/sem5_lastday.jpg', caption: 'Semester 5 Last Day' },
  { id: 'sem6', src: '/memories/sem6_lastday.jpg', caption: 'Semester 6 Last Day' },
  { id: 'sem7', src: '/memories/sem7_lastday.jpg', caption: 'Semester 7 Last Day' },
  { id: 'sem8', src: '/memories/sem8_lastday.jpg', caption: 'Semester 8 Last Day' },
  { id: 'diksha', src: '/memories/Diksha.jpg', caption: 'Diksha' },
  { id: 'diksha_2', src: '/memories/Diksha(2).jpg', caption: 'Diksha (2)' },
  { id: 'diksha_3', src: '/memories/Diksha(3).jpg', caption: 'Diksha (3)' },
  { id: 'diksha_4', src: '/memories/Diksha(4).jpg', caption: 'Diksha (4)' },
  { id: 'diksha_5', src: '/memories/Diksha(5).jpg', caption: 'Diksha (5)' },
  { id: 'diksha_6', src: '/memories/Diksha(6).jpg', caption: 'Diksha (6)' },
  { id: 'diksha_7', src: '/memories/Diksha(7).jpg', caption: 'Diksha (7)' },
  { id: 'diksha_8', src: '/memories/Diksha(8).jpg', caption: 'Diksha (8)' },
  { id: 'diksha_9', src: '/memories/Diksha(9).jpg', caption: 'Diksha (9)' },
  { id: 'diksha_10', src: '/memories/Diksha(10).jpg', caption: 'Diksha (10)' },
  { id: 'diksha_11', src: '/memories/Diksha(11).jpg', caption: 'Diksha (11)' },
  { id: 'diksha_12', src: '/memories/Diksha(12).jpg', caption: 'Diksha (12)' },
  { id: 'diksha_13', src: '/memories/Diksha(13).jpg', caption: 'Diksha (13)' },
]
