export interface Memory {
  id: string
  type: 'image' | 'gif' | 'audio'
  src: string
  width: number
  height: number
  caption: string
  date?: string
}

export const memories: Memory[] = [
  {
    id: 'mem1',
    type: 'image',
    src: '/Memory_Wall/1.webp',
    width: 400,
    height: 400,
    caption: 'Memory 1',
  },
  {
    id: 'mem2',
    type: 'image',
    src: '/Memory_Wall/2.webp',
    width: 400,
    height: 400,
    caption: 'Memory 2',
  },
  {
    id: 'mem3',
    type: 'image',
    src: '/Memory_Wall/3.webp',
    width: 400,
    height: 400,
    caption: 'Memory 3',
  },
  {
    id: 'mem4',
    type: 'image',
    src: '/Memory_Wall/4.webp',
    width: 400,
    height: 400,
    caption: 'Memory 4',
  },
  {
    id: 'mem5',
    type: 'image',
    src: '/Memory_Wall/5.webp',
    width: 400,
    height: 400,
    caption: 'Memory 5',
  },
  {
    id: 'mem6',
    type: 'image',
    src: '/Memory_Wall/6.webp',
    width: 400,
    height: 400,
    caption: 'Memory 6',
  },
  {
    id: 'mem7',
    type: 'image',
    src: '/Memory_Wall/7.webp',
    width: 400,
    height: 400,
    caption: 'Memory 7',
  },
  {
    id: 'mem8',
    type: 'image',
    src: '/Memory_Wall/8.webp',
    width: 400,
    height: 400,
    caption: 'Memory 8',
  },
  {
    id: 'mem9',
    type: 'image',
    src: '/Memory_Wall/9.webp',
    width: 400,
    height: 400,
    caption: 'Memory 9',
  },
  {
    id: 'mem10',
    type: 'image',
    src: '/Memory_Wall/10.webp',
    width: 400,
    height: 400,
    caption: 'Memory 10',
  },
  {
    id: 'mem11',
    type: 'image',
    src: '/Memory_Wall/11.webp',
    width: 400,
    height: 400,
    caption: 'Memory 11',
  },
  {
    id: 'mem12',
    type: 'image',
    src: '/Memory_Wall/12.webp',
    width: 400,
    height: 400,
    caption: 'Memory 12',
  },
  {
    id: 'mem13',
    type: 'image',
    src: '/Memory_Wall/13.webp',
    width: 400,
    height: 400,
    caption: 'Memory 13',
  },
  {
    id: 'mem14',
    type: 'image',
    src: '/Memory_Wall/14.webp',
    width: 400,
    height: 400,
    caption: 'Memory 14',
  },
  {
    id: 'mem15',
    type: 'image',
    src: '/Memory_Wall/15.webp',
    width: 400,
    height: 400,
    caption: 'Memory 15',
  },
  {
    id: 'mem16',
    type: 'image',
    src: '/Memory_Wall/Aapki_taste_gaane-prr.jpeg',
    width: 738,
    height: 1273,
    caption: 'Aapki Taste',
  },
  {
    id: 'mem17',
    type: 'image',
    src: '/Memory_Wall/First_approach_on_food.jpeg',
    width: 1080,
    height: 910,
    caption: 'First Approach',
  },
  {
    id: 'mem18',
    type: 'image',
    src: '/Memory_Wall/Manati_hui_dost.jpeg',
    width: 1080,
    height: 1030,
    caption: 'Manati Hui Dost',
  },
  {
    id: 'mem19',
    type: 'image',
    src: '/Memory_Wall/Mera_invite.jpeg',
    width: 1080,
    height: 901,
    caption: 'Mera Invite',
  },
]
